[[manager.prepend_keymap]]
on   = [ "i" ]
run  = "plugin keyjump --args=global"
desc = "Keyjump (Global mode)"

[[manager.prepend_keymap]]
on  = [ "T" ]
run = "plugin --sync max-preview"
[[manager.prepend_keymap]]
on  = [ "T" ]
run = "plugin --sync hide-preview"
