[headsup]
disable_exec_warn = true

[opener]
edit = [
	{ run = 'nvim "$@"', desc = "neovim", block = true },
]
open = [
	{ run = 'handlr open "$@"', desc = "handlr open", block = true },
]
[open]
prepend_rules = [
    	{ name = "*.md", use = ["edit", "open"] },
]


[plugin]
prepend_previewers = [
    { name = "*.md", run = "glow" },
]
